/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        /**
          * Title prop
         */
        "title": string;
    }
}
declare global {
    interface HTMLAppSideDrawerElement extends Components.AppSideDrawer, HTMLStencilElement {
    }
    var HTMLAppSideDrawerElement: {
        prototype: HTMLAppSideDrawerElement;
        new (): HTMLAppSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "app-side-drawer": HTMLAppSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface AppSideDrawer {
        "opened"?: boolean;
        /**
          * Title prop
         */
        "title"?: string;
    }
    interface IntrinsicElements {
        "app-side-drawer": AppSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-side-drawer": LocalJSX.AppSideDrawer & JSXBase.HTMLAttributes<HTMLAppSideDrawerElement>;
        }
    }
}
